source 'https://rubygems.org'
ruby '2.6.3'
gem 'ginseng-core', git: 'https://github.com/pooza/ginseng-core.git'
gem 'ginseng-web', git: 'https://github.com/pooza/ginseng-web.git'
gem 'nokogiri'
gem 'rubocop'
gem 'sanitize'
