source 'https://rubygems.org'
ruby '2.6.5'
gem 'bootsnap'
gem 'ginseng-core', git: 'https://github.com/pooza/ginseng-core.git'
gem 'ginseng-web', git: 'https://github.com/pooza/ginseng-web.git'
gem 'nokogiri'
gem 'rubocop'
gem 'rubocop-performance'
gem 'sanitize'
