package:
  version: 1.2.6
  url: https://github.com/pooza/cucumber-feed
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
feeds:
  - abc
  - garden
  - toei
  - toei_startwinkle
  - miracle_universe