package:
  version: 1.3.22
  url: https://github.com/pooza/cucumber-feed
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
feeds:
  - abc
  - garden
  - toei
  - miracle_leap
puma:
  port: 3003
  pidfile: tmp/pids/puma.pid
  rackup: app/initializer/config.ru
