package:
  version: 1.3.12
  url: https://github.com/pooza/cucumber-feed
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
feeds:
  - abc
  - garden
  - toei
  - star_twincle_movie
