package:
  version: 1.3.19
  url: https://github.com/pooza/cucumber-feed
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
feeds:
  - abc
  - garden
  - toei
  - miracle_leap
thin:
  timeout: 30
  port: 3003
  environment: production
  rackup: app/initializer/config.ru
