package:
  version: 1.4.0
  url: https://github.com/pooza/cucumber-feed
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
  license: MIT
environment: development
feeds:
  - abc
  - garden
  - toei
  - miracle_leap
puma:
  port: 3003
  pidfile: tmp/pids/puma.pid
  rackup: app/initializer/config.ru
test:
  timeout: 20
  filters:
    - name: ci
      cases: []
