package:
  version: 0.5.1
  url: https://github.com/pooza/cucumber-feed
external_urls:
  mechokku: https://docs.google.com/spreadsheets/d/1tvVK9m09UfzQebd_VHORgOSoIkw_Cj3xi2m_zdys5Rw
author: pooza@b-shock.org
minutes: 5
