package:
  version: 1.4.1
  url: https://github.com/pooza/cucumber-feed
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
  license: MIT
environment: development
feeds:
  - abc
  - garden
  - toei
  - tropical_rouge
puma:
  port: 3003
  pidfile: tmp/pids/puma.pid
  rackup: app/initializer/config.ru
test:
  timeout: 20
  filters:
    - name: ci
      cases:
        - abc_feed_renderer
        - garden_feed_renderer
        - miracle_leap_feed_renderer
        - toei_feed_renderer
