package:
  version: 1.3.2
  url: https://github.com/pooza/cucumber-feed
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
cert:
  url: https://curl.haxx.se/ca/cacert.pem
feeds:
  - abc
  - garden
  - toei
  - miracle_universe
